apiVersion: v1
kind: Service
metadata:
 name: my-first-deployment
 labels:
   app: my-first-deployment
spec:
 type: NodePort
 selector:
   app: my-first-deployment
 ports:
  - port: 8080
    nodePort: 32410